#480 Automatic Coproduct Rename from/to Protobuf GeneratedEnum
scalalandio/chimney pull request #489
Opened 2024-04-01 18:47 UTC by saeltz

I'm not entirely happy with the `TransformedNamesComparison` because it matches too broadly. I'm open for better suggestions.

I want to achieve a comparison for the following:

```
enum Field {
  FIELD_UNSPECIFIED = 0;
  FIELD_CASE_ONE = 1;
  FIELD_CASE_TWO = 2;
}
```

From/To

```
enum Field:
  case One, Two
```

2024-04-02 11:54 UTC, MateuszKubuszok requested changes
Thank you for the effort! I left a comment.

2024-04-02 11:54 UTC, MateuszKubuszok commented on chimney/src/main/scala/io/scalaland/chimney/dsl/TransformedNamesComparison.scala
> +  case object GeneratedProtobufEnumEquality extends TransformedNamesComparison {
I would either name it `CamelCaseUnderscoreCaseEquality` (to e.g. use this with Java enums as well, maybe it should be a default for it? Maybe it should be named `JavaEnumAware`?) or keep it in `chimneyProtobuf` module. I wouldn't put some integration-specific conventions in the core package.

2024-04-24 08:53 UTC, MateuszKubuszok commented
Hey @saeltz 👋 , do you still want to work on this?

2024-04-29 19:41 UTC, closed without merging

2024-04-29 19:41 UTC, saeltz commented
Hey @MateuszKubuszok, this currently matches too broadly. For this special use case I would probably rather go for something like https://github.com/moia-oss/teleproto/pull/326 by @lbialy.

2024-06-08 15:09 UTC, MateuszKubuszok commented
@saeltz - if you want to use Chimney in your macro-logic, with [1.1.0](https://github.com/scalalandio/chimney/releases/tag/1.1.0) it would be possible to just use Chimney macros directly. Please, open a discussion if you are interested in this.